# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_q11(self):
    self.driver.get("https://qa.foureyesinsight.uk/portal/login")
    self.driver.set_window_size(884, 980)
    time.sleep(2)
    self.driver.find_element(By.ID, "email").send_keys("Test.User+1@foureyesinsight.com")
    time.sleep(2)
    self.driver.find_element(By.ID, "password").send_keys("#InterVIEW123!")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#submit-button > span").click()
    time.sleep(5)
    get_url = self.driver.current_url
    assert(get_url == "https://qa.foureyesinsight.uk/portal/home")
  
